export const getColorClasses = (color) => {
  const colorMap = {
    neutral: {
      bg: 'bg-white/10',
      bgLight: 'bg-white/5',
      bgMedium: 'bg-white/10',
      text: 'text-text-primary',
      border: 'border-white/20',
      borderLight: 'border-white/15',
      borderMedium: 'border-white/20',
    },
    red: {
      bg: 'bg-accent-red',
      bgLight: 'bg-accent-red/20',
      bgMedium: 'bg-accent-red/30',
      text: 'text-white',
      border: 'border-accent-red',
      borderLight: 'border-accent-red/50',
      borderMedium: 'border-accent-red',
    },
    mint: {
      bg: 'bg-accent-green',
      bgLight: 'bg-accent-green/15',
      bgMedium: 'bg-accent-green/25',
      text: 'text-accent-green',
      border: 'border-accent-green',
      borderLight: 'border-accent-green/30',
      borderMedium: 'border-accent-green/40',
    },
    cyan: {
      bg: 'bg-accent-blue',
      bgLight: 'bg-accent-blue/15',
      bgMedium: 'bg-accent-blue/25',
      text: 'text-accent-blue',
      border: 'border-accent-blue',
      borderLight: 'border-accent-blue/30',
      borderMedium: 'border-accent-blue/40',
    },
    amber: {
      bg: 'bg-accent-orange',
      bgLight: 'bg-accent-orange/15',
      bgMedium: 'bg-accent-orange/25',
      text: 'text-accent-orange',
      border: 'border-accent-orange',
      borderLight: 'border-accent-orange/30',
      borderMedium: 'border-accent-orange/40',
    },
    yellow: {
      bg: 'bg-accent-yellow',
      bgLight: 'bg-accent-yellow/15',
      bgMedium: 'bg-accent-yellow/25',
      text: 'text-accent-yellow',
      border: 'border-accent-yellow',
      borderLight: 'border-accent-yellow/30',
      borderMedium: 'border-accent-yellow/40',
    },
    purple: {
      bg: 'bg-purple-400',
      bgLight: 'bg-purple-400/15',
      bgMedium: 'bg-purple-400/25',
      text: 'text-purple-400',
      border: 'border-purple-400',
      borderLight: 'border-purple-400/30',
      borderMedium: 'border-purple-400/40',
    },
    pink: {
      bg: 'bg-pink-accent',
      bgLight: 'bg-pink-accent/15',
      bgMedium: 'bg-pink-accent/25',
      text: 'text-pink-accent',
      border: 'border-pink-accent',
      borderLight: 'border-pink-accent/30',
      borderMedium: 'border-pink-accent/40',
    },
    default: {
      bg: 'bg-white/10',
      bgLight: 'bg-white/5',
      bgMedium: 'bg-white/10',
      text: 'text-text-primary',
      border: 'border-white/20',
      borderLight: 'border-white/15',
      borderMedium: 'border-white/20',
    },
  }
  return colorMap[color] || colorMap.default
}
